package com.diniz.springbootstudy.entities.exemp;

import com.diniz.springbootstudy.entities.User;
import com.diniz.springbootstudy.entities.enums.OrderStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonRootName;
import jakarta.persistence.*;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

@Entity
@Table(name = "tb_order") // Table's name
@JsonRootName(value = "order") // Defines the parent JSON key
public class Order implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    // Primary key.
    // The database automatically generates the identifier.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Defines how the Instant value is serialized/deserialized in JSON.
    // Example: "2026-08-14T16:30:00Z"
    @JsonFormat(
            shape = JsonFormat.Shape.STRING,
            pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'",
            timezone = "GMT"
    )
    private Instant moment;

    /*
     * Stores the order status as an Integer instead of an enum.
     *
     * Why?
     *
     * JPA/Hibernate persists primitive values more easily than enums.
     *
     * Example during object creation:
     *
     * OrderStatus.PAID
     *          │
     *          ▼
     * status.getCode()
     *          │
     *          ▼
     * returns:
     *
     *      2
     *          │
     *          ▼
     * orderStatus = 2
     *          │
     *          ▼
     * Database column:
     *
     * +--------------+
     * | order_status |
     * +--------------+
     * |      2       |
     * +--------------+
     *
     * Later, when the entity is loaded:
     *
     * Database
     *      │
     *      ▼
     * order_status = 2
     *      │
     *      ▼
     * orderStatus = 2
     *      │
     *      ▼
     * getStatus()
     *      │
     *      ▼
     * OrderStatus.PAID
     */
    private Integer orderStatus;

    /*
     * Entity Relationship
     *
     * +----------------+           +----------------+
     * |     User       | 1       N |     Order      |
     * +----------------+-----------+----------------+
     * | id (PK)        | <---------| client_id (FK) |
     * | email          |           | id (PK)        |
     * | name           |           | moment         |
     * | password       |           +----------------+
     * | phone          |
     * +----------------+
     *
     * Many Orders can belong to the same User.
     * Each Order belongs to one User.
     *
     * @ManyToOne maps the relationship between Order and User.
     *
     * @JoinColumn(name = "client_id") specifies the foreign key
     * column in the Order table.
     *
     * Generated table:
     *
     * CREATE TABLE tb_order (
     *     client_id BIGINT,
     *     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     *     moment TIMESTAMP WITH TIME ZONE,
     *     order_status INTEGER,
     *     PRIMARY KEY (id)
     * );
     *
     * Foreign key:
     *
     * tb_order.client_id  ----------->  tb_user.id
     */
    @ManyToOne
    @JoinColumn(name = "client_id")
    private User client;

    public Order() {
    }

    /*
     * Object creation flow
     *
     * Example:
     *
     * new Order(
     *      1L,
     *      Instant.now(),
     *      OrderStatus.PAID,
     *      user
     * )
     *          │
     *          ▼
     * status = OrderStatus.PAID
     *          │
     *          ▼
     * setStatus(status)
     *          │
     *          ▼
     * status.getCode()
     *          │
     *          ▼
     * returns:
     *
     *      2
     *          │
     *          ▼
     * orderStatus = 2
     *
     * Result:
     *
     * The application works with the enum,
     * while the entity stores its numeric code.
     */
     // OrderStatus enum_status -> its not the class order attribute, but comes directly from enum
    public Order(Long id, Instant moment, OrderStatus enum_status, User client) {
        this.id = id;
        this.moment = moment;
        setStatus(enum_status); // here we send the enum_status from de enum to the local attribute orderStatus, which is an Integer
        this.client = client;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Instant getMoment() {
        return moment;
    }

    public void setMoment(Instant moment) {
        this.moment = moment;
    }

    /*
     * Converts the stored Integer into an OrderStatus enum.
     *
     * Execution flow:
     *
     * Database value:
     *
     *      enum_status = 2
     *              │
     *              ▼
     * Hibernate loads:
     *
     *      orderStatus = 2
     *              │
     *              ▼
     * getStatus()
     *              │
     *              ▼
     * OrderStatus.valueOf(2)
     *              │
     *              ▼
     * valueOf() checks every enum constant:
     *
     * WAITING_PAYMENT -> code = 1
     * PAID            -> code = 2 ✔ Match
     *
     * Returned value:
     *
     * OrderStatus.PAID
     */
    //enum
    public OrderStatus getStatus() {
        /*
          * getStatus() is a getter method that retrieves the order status as an enum.
          * It converts the stored Integer value (orderStatus) into the corresponding OrderStatus enum.

          *  here the method get the value saved on orderStatus(Integer)
          * and convert it to the enum OrderStatus using the valueOf() method
         */
        return OrderStatus.valueOf(orderStatus);
    }

    /*
     * Converts an OrderStatus enum into its numeric code.
     *
     * Example:
     *
     * OrderStatus.PAID
     *          │
     *          ▼
     * setStatus(OrderStatus.PAID)
     *          │
     *          ▼
     * status.getCode()
     *          │
     *          ▼
     * returns:
     *
     *      2
     *          │
     *          ▼
     * orderStatus = 2
     *          │
     *          ▼
     * Hibernate persists:
     *
     * order_status = 2
     *
     * The application manipulates enums,
     * but the database stores integers.
     */
    public void setStatus(OrderStatus enum_status) {
        if (enum_status != null) {
            this.orderStatus = enum_status.getCode();
        }
    }

    public User getClient() {
        return client;
    }

    public void setClient(User client) {
        this.client = client;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(id, order.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}