package com.diniz.springbootstudy.controllers;

import com.diniz.springbootstudy.dto.AuthenticationDTO;
import com.diniz.springbootstudy.dto.ForgotPasswordDTO;
import com.diniz.springbootstudy.dto.LoginResponseDTO;
import com.diniz.springbootstudy.dto.ResetPasswordDTO;
import com.diniz.springbootstudy.entities.User;
import com.diniz.springbootstudy.services.security.PasswordResetService;
import com.diniz.springbootstudy.services.security.TokenService;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Objects;

// ============================================================================
// AUTHENTICATION CONTROLLER
// ============================================================================
// Endpoint controller responsible for user authentication and password recovery.
// Base path: /auth
// ============================================================================

@RestController
// Tells Spring this class handles RESTful HTTP requests and converts return values directly into JSON responses.
@RequestMapping("/auth") // Maps all endpoints within this controller under the "/auth" base URL route.
public class AuthenticationController {

    // Final fields enforce immutability after constructor injection.
    private final AuthenticationManager authenticationManager;
    private final TokenService tokenService;
    private final PasswordResetService passwordResetService;

    /**
     * Dependency Injection via Constructor (Spring Best Practice).
     * Spring automatically resolves and provides the required service beans at runtime.
     * Using constructor injection simplifies unit testing and avoids field injection issues (@Autowired).
     */
    public AuthenticationController(
            AuthenticationManager authenticationManager,
            TokenService tokenService,
            PasswordResetService passwordResetService
    ) {
        this.authenticationManager = authenticationManager;
        this.tokenService = tokenService;
        this.passwordResetService = passwordResetService;
    }

    /*
     * Endpoint: POST:http://localhost:8080/auth/login
     * Receives email and password, authenticates credentials against BCrypt password hashes in the database,
     * and returns a signed JWT access token for subsequent authenticated requests.
     */
    @PostMapping("/login")
    /*
     * Method signature details:
     * - @RequestBody: Deserializes incoming JSON request body into the AuthenticationDTO object.
     * - @Valid: Triggers Bean Validation constraints (e.g., @NotBlank, @Email) defined inside AuthenticationDTO.
     * - ResponseEntity<LoginResponseDTO>: Wraps the HTTP response status code (200 OK) and payload body.
     *
     * (Request) AuthenticationDTO  -> DTO carrying user email and password credentials.
     * (Response) LoginResponseDTO -> DTO encapsulation containing the generated JWT token string.
     */
    public ResponseEntity<LoginResponseDTO> login(@RequestBody @Valid AuthenticationDTO data) {

        /*
         * STEP 1: Wrap raw incoming user credentials into an unauthenticated Authentication object.
         *
         * UsernamePasswordAuthenticationToken -> Native Spring Security class.
         * Uses the 2-argument constructor (principal, credentials) to wrap unauthenticated credentials (sets authenticated = false).
         * Note: This class only holds data; the actual authentication logic is performed later by AuthenticationManager.
         */

        // EXPLICIT DECLARATION (Visible Type)
        UsernamePasswordAuthenticationToken usernamePassword =
                new UsernamePasswordAuthenticationToken(data.email(), data.password());

        /*
         * SYNTAX NOTE - EQUIVALENT WITH 'var' (Type Inference - Java 10+):
         * The compiler automatically infers the type from the 'new' operator.
         * At runtime, performance and generated bytecode are identical.
         *
         * var usernamePassword = new UsernamePasswordAuthenticationToken(data.email(), data.password());
         */

        /*
         * STEP 2: Trigger Spring Security authentication workflow under the hood.
         * The AuthenticationManager interface delegates to ProviderManager (specifically DaoAuthenticationProvider):
         *   a) Calls your UserDetailsService.loadUserByUsername() to query the user record from the database.
         *   b) Compares the raw incoming password against the stored BCrypt hash using PasswordEncoder.
         *   c) If invalid, automatically throws BadCredentialsException (returning HTTP 401 Unauthorized or 403 Forbidden).
         *   d) If valid, returns a fully authenticated Authentication object containing granted authorities/roles.
         *
         * POLYMORPHISM IN ACTION:
         * 1. Explicit Type (Polymorphic Reference): 'auth' is typed as the Authentication interface,
         *    but holds a concrete implementation (UsernamePasswordAuthenticationToken) at runtime.
         * 2. Method Polymorphism: 'authenticationManager' invokes the interface contract, while Spring
         *    executes its underlying implementation (ProviderManager).
         */
        Authentication auth = this.authenticationManager.authenticate(usernamePassword);

        /*
         * SYNTAX NOTE - EQUIVALENT WITH 'var' (Type Inference - Java 10+):
         * The compiler automatically infers 'auth' as the Authentication interface return type.
         *
         * var auth = this.authenticationManager.authenticate(usernamePassword);
         */

        /*
         * STEP 3: Retrieve the authenticated User entity and generate the JWT token.
         * - auth.getPrincipal(): Returns the authenticated User principal object loaded during step 2.
         * - Objects.requireNonNull(): Ensures the principal is non-null before casting to prevent NPE bugs.
         * - Cast to (User): Safely casts the generic principal object to our domain User entity.
         * - tokenService.generateToken(): Encodes claims (e.g., subject, expiration time) and signs the JWT using a secret key.
         */
        var token = tokenService.generateToken((User) Objects.requireNonNull(auth.getPrincipal()));

        /*
         * STEP 4: Build and return the successful HTTP response.
         * Wraps the JWT string inside a LoginResponseDTO object and returns HTTP status 200 OK.
         */
        return ResponseEntity.ok(new LoginResponseDTO(token));
    }

    // ========================================================================
    // PASSWORD RECOVERY ENDPOINTS
    // ========================================================================

    /*
     * Endpoint: POST :http://localhost:8080/auth/forgot-password
     * Generates a password reset token for the specified user account and dispatches a recovery email.
     *
     * Request Body: ForgotPasswordDTO (contains target email address).
     * Response: HTTP 204 No Content (Standard REST practice when no response body needs to be returned).
     */
    @PostMapping("/forgot-password")
    public ResponseEntity<Void> forgotPassword(@RequestBody @Valid ForgotPasswordDTO dto) {

        /*
         * Delegates reset token creation, expiration management (e.g., 30-min window),
         * and email dispatch logic to PasswordResetService.
         */
        passwordResetService.createPasswordResetToken(dto);// sends the dto with the email to the service layer, which handles token generation and email sending

        /*
         * Returns HTTP status 204 No Content to indicate the request was accepted and processed successfully.
         */
        return ResponseEntity.noContent().build();
    }

    /*
     * Endpoint: POST /auth/reset-password
     * Validates an existing reset token and updates the target user's password with a new BCrypt hash.
     *
     * Request Body: ResetPasswordDTO (contains reset token string and new password).
     * Response: HTTP 204 No Content.
     */
    @PostMapping("/reset-password")
    public ResponseEntity<Void> resetPassword(@RequestBody @Valid ResetPasswordDTO dto) {

        /*
         * Verifies token validity/expiration and updates the user's password hash in the database.
         */
        passwordResetService.resetPassword(dto);

        /*
         * Returns HTTP status 204 No Content confirming successful password update.
         */
        return ResponseEntity.noContent().build();
    }
}