package com.diniz.springbootstudy.entities;

import jakarta.persistence.*;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

@Entity
@Table(name = "tb_order") // Table´s name
public class Order implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    // Delegates ID generation to the database auto-increment feature
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Instant moment;

    /*
     * Entity Relationship
     *
     * +----------------+           +----------------+
     * |     User       | 1       N |     Order      |
     * +----------------+-----------+----------------+
     * | id (PK)        | <---------| client_id (FK) |
     * | email          |           | id (PK)        |
     * | name           |           | moment         |
     * | password       |           +----------------+
     * | phone          |
     * +----------------+
     *
     * Many Orders can belong to the same User.
     * Each Order belongs to one User.
     *
     * @ManyToOne maps the relationship between Order and User.
     *
     * @JoinColumn(name = "client_id") specifies the foreign key
     * column in the Order table.
     *
     * In practice, Hibernate generates the following table:
     *
     * CREATE TABLE tb_order (
     *     client_id BIGINT,
     *     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     *     moment TIMESTAMP(6) WITH TIME ZONE,
     *     PRIMARY KEY (id)
     * );
     *
     * Hibernate then creates the foreign key:
     *
     * ALTER TABLE IF EXISTS tb_order
     *     ADD CONSTRAINT ...
     *     FOREIGN KEY (client_id)
     *     REFERENCES tb_user;
     *
     * Therefore:
     *
     *     tb_order.client_id  ──────────>  tb_user.id
     *          (FK)                         (PK)
     */
    @ManyToOne
    @JoinColumn(name = "client_id")
    private User client;

    public Order() {
    }

    public Order(Long id, Instant moment, User client) {
        this.id = id;
        this.moment = moment;
        this.client = client;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Instant getMoment() {
        return moment;
    }

    public void setMoment(Instant moment) {
        this.moment = moment;
    }

    public User getClient() {
        return client;
    }

    public void setClient(User client) {
        this.client = client;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(id, order.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
