package com.diniz.springbootstudy.entities;

import com.diniz.springbootstudy.entities.enums.OrderStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonRootName;
import jakarta.persistence.*;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

@Entity
@Table(name = "tb_order") // Table´s name
@JsonRootName(value = "order") // <-- Define o nome da chave pai
public class Order implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    //- first column in the table is the primary key, which is auto-generated by the database.
    @Id
    // Delegates ID generation to the database auto-increment feature
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Defines how the Instant value is serialized/deserialized in JSON.
    // The date is formatted as ISO-8601 UTC format: yyyy-MM-dd'T'HH:mm:ss'Z'
    // Example: "2026-08-14T16:30:00Z"
    @JsonFormat(
            shape = JsonFormat.Shape.STRING,
            pattern = "yyyy-MM-dd'T'HH:mm:ss'Z'",
            timezone = "GMT"
    )
    private Instant moment;


    /*
            Seed
           ↓
    OrderStatus.PAID
       ↓
    setStatus()
       ↓
    orderStatus = 2
       ↓
    Banco salva Integer
     */
    private Integer orderStatus;

    /*
     * Entity Relationship
     *
     * +----------------+           +----------------+
     * |     User       | 1       N |     Order      |
     * +----------------+-----------+----------------+
     * | id (PK)        | <---------| client_id (FK) |
     * | email          |           | id (PK)        |
     * | name           |           | moment         |
     * | password       |           +----------------+
     * | phone          |
     * +----------------+
     *
     * Many Orders can belong to the same User.
     * Each Order belongs to one User.
     *
     * @ManyToOne maps the relationship between Order and User.
     *
     * @JoinColumn(name = "client_id") specifies the foreign key
     * column in the Order table.
     *
     * In practice, Hibernate generates the following table:
     *
     * CREATE TABLE tb_order (
     *     client_id BIGINT,
     *     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     *     moment TIMESTAMP(6) WITH TIME ZONE,
     *     PRIMARY KEY (id)
     * );
     *
     * Hibernate then creates the foreign key:
     *
     * ALTER TABLE IF EXISTS tb_order
     *     ADD CONSTRAINT ...
     *     FOREIGN KEY (client_id)
     *     REFERENCES tb_user;
     *
     * Therefore:
     *
     *     tb_order.client_id  ──────────>  tb_user.id
     *          (FK)                         (PK)
     */
    @ManyToOne
    @JoinColumn(name = "client_id")
    private User client;


    public Order() {
    }


    public Order(Long id, Instant moment, OrderStatus status, User client) {
        this.id = id;
        this.moment = moment;
        setStatus(status);
        this.client = client;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Instant getMoment() {
        return moment;
    }

    public void setMoment(Instant moment) {
        this.moment = moment;
    }

    /*
     * Converts the stored integer code into the corresponding enum.
     *
     * Example:
     * Database value: 2
     * Returns: OrderStatus.PAID
     */
    public OrderStatus getStatus() {
        return OrderStatus.valueOf(orderStatus);
    }

    /*
     * Converts the enum into its numeric code before storing it.
     *
     * Example:
     * OrderStatus.PAID -> 2
     */
    public void setStatus(OrderStatus status) {
        if (status != null) {
            this.orderStatus = status.getCode();
        }
    }

    public User getClient() {
        return client;
    }

    public void setClient(User client) {
        this.client = client;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return Objects.equals(id, order.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
