package com.diniz.springbootstudy.entities;

import jakarta.persistence.*;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

@Entity
@Table(name = "tb_payment")
public class Payment implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /*
     * Primary key.
     * Note: We DO NOT use @GeneratedValue(strategy = GenerationType.IDENTITY) here.
     * Because of the @MapsId annotation on the 'order' field below, this Payment entity
     * inherits and shares the exact same primary key value generated by the associated
     * Order01 entity. The ID is still automatically generated, but through the Order01 sequence.
     */
    @Id
    private Long id;

    private Instant moment;

    /*
     * The Payment entity is the dependent entity because an Order
     * can exist without a Payment, but a Payment cannot exist
     * without an associated Order.
     *
     * Relationship:
     * - An Order has one Payment.
     * - A Payment belongs to one Order.
     *
     * The @MapsId annotation indicates that Payment shares the same
     * primary key value as the associated Order entity.
     */
    @OneToOne
    @MapsId
    @JoinColumn(name = "order_id")
    private Order01 order;

    public Payment() {
    }

    public Payment(Long id, Instant moment, Order01 order) {
        this.id = id;
        this.moment = moment;
        this.order = order;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Instant getMoment() {
        return moment;
    }

    public void setMoment(Instant moment) {
        this.moment = moment;
    }

    public Order01 getOrder() {
        return order;
    }

    public void setOrder(Order01 order) {
        this.order = order;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Payment payment = (Payment) o;
        return Objects.equals(id, payment.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}