package com.diniz.springbootstudy.entities;

import com.diniz.springbootstudy.entities.exemp.Order;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

// Marks this class as a JPA entity managed by Hibernate
@Entity
// Specifies the custom database table name ('tb_user' instead of default 'User')
@Table(name = "tb_user") // Table´s name
public class User implements Serializable {

    // Identifies the field used for class serialization compatibility
    @Serial
    private static final long serialVersionUID = 1L;

    // Marks this field as the primary key of the table
    @Id
    // Delegates ID generation to the database auto-increment feature
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    @Column(unique = true) // <-- Garante a unicidade do e-mail na tabela do banco de dados
    private String email;

    private String phone;

    @JsonIgnore // <-- Impede a exibição da senha nas respostas JSON
    private String password;

    /*
     * Entity Relationship
     *
     * +----------------+           +----------------+
     * |     User       | 1       N |     Order      |
     * +----------------+-----------+----------------+
     * | id (PK)        |           | id (PK)        |
     * | email          |           | moment         |
     * | name           |           | client_id (FK) |
     * | password       |           +----------------+
     * | phone          |
     * +----------------+
     *
     * One User can have many Orders.
     * Each Order belongs to one User.
     *
     * The "orders" attribute represents the collection of orders
     * associated with this user.
     *
     * @OneToMany defines the one-to-many relationship.
     * "mappedBy = client" indicates that the relationship is mapped
     * by the "client" attribute in the Order entity.
     *
     * In practice, Hibernate generates the following table:
     *
     * CREATE TABLE tb_user (
     *     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     *     email VARCHAR(255) UNIQUE,
     *     name VARCHAR(255),
     *     password VARCHAR(255),
     *     phone VARCHAR(255),
     *     PRIMARY KEY (id)
     * );
     *
     * Hibernate then creates the foreign key relationship:
     *
     * ALTER TABLE IF EXISTS tb_order
     *     ADD CONSTRAINT ...
     *     FOREIGN KEY (client_id)
     *     REFERENCES tb_user;
     *
     * Therefore:
     *
     *     tb_order.client_id  ──────────>  tb_user.id
     *          (FK)                         (PK)
     * *
     * *http://localhost:8080/h2-console
     */
    @JsonIgnore // <-- Bloqueia a referência circular no GET /orders
    @OneToMany(mappedBy = "client")
    private List<Order> orders = new ArrayList<>();

    public User() {}

    // Construtor corrigido: name vem antes de email
    public User(Long id, String name, String email, String phone, String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // Returns the user's orders, only get ´cause the collection can not be altered
    public List<Order> getOrders() {
        return orders;
    }

    // Overrides default Object equals to compare entities by ID
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(id, user.id);
    }

    // Overrides default Object hashCode based on the unique ID
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}