package com.diniz.springbootstudy.dto.admin;

import com.diniz.springbootstudy.dto.CategoryDTO;
import com.diniz.springbootstudy.entities.OrderItem;
import com.diniz.springbootstudy.entities.Product;
import com.fasterxml.jackson.annotation.JsonRootName;

import java.io.Serial;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

// ============================================================================
// ADMIN DTO - COMPREHENSIVE PRODUCT ANALYTICS & MANAGEMENT VIEW
// ============================================================================
// Purpose:
// Designed exclusively for the Backoffice / Admin Dashboard.
// Enriches basic product metadata with business KPIs (total sold, revenue)
// and an audit trail of orders where this product was purchased.
// ============================================================================

/**
 * Administrative Product DTO containing catalog details, sales KPIs,
 * and associated order summaries.
 */
@JsonRootName(value = "productAdmin")
public class ProductAdminDTO implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String description;
    private Double price;
    private String imgUrl;

    // Business KPIs
    private Integer totalOrdersCount;
    private Integer totalUnitsSold;
    private Double totalRevenueGenerated;

    private Set<CategoryDTO> categories = new HashSet<>();
    private Set<OrderSummaryAdminDTO> ordersSummary = new HashSet<>();

    public ProductAdminDTO() {
    }

    /**
     * Entity Conversion Constructor (ADMIN USE).
     *
     * Extracts catalog data, maps associated categories, calculates sales KPIs
     * using Stream API, and maps associated orders to summarized DTOs.
     *
     * @param entity Source Product JPA entity.
     */
    public ProductAdminDTO(Product entity) {
        this.id = entity.getId();
        this.name = entity.getName();
        this.description = entity.getDescription();
        this.price = entity.getPrice();
        this.imgUrl = entity.getImgUrl();

        // 1. Map Categories via Stream API
        if (entity.getCategories() != null) {
            this.categories = entity.getCategories().stream()
                    .map(CategoryDTO::new)
                    .collect(Collectors.toSet());
        }

        // 2. Process Sales KPIs & Orders Summary via Stream API
        if (entity.getItems() != null && !entity.getItems().isEmpty()) {

            // Calculate total units sold across all orders
            this.totalUnitsSold = entity.getItems().stream()
                    .mapToInt(OrderItem::getQuantity)
                    .sum();

            // Calculate total revenue generated by this product
            this.totalRevenueGenerated = entity.getItems().stream()
                    .mapToDouble(OrderItem::getSubTotal)
                    .sum();

            // Map unique Orders to OrderSummaryAdminDTO
            this.ordersSummary = entity.getItems().stream()
                    .map(OrderItem::getOrder)
                    .map(OrderSummaryAdminDTO::new)
                    .collect(Collectors.toSet());

            this.totalOrdersCount = this.ordersSummary.size();
        } else {
            this.totalOrdersCount = 0;
            this.totalUnitsSold = 0;
            this.totalRevenueGenerated = 0.0;
        }
    }

    // ============================================================================
    // GETTERS AND SETTERS
    // ============================================================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Integer getTotalOrdersCount() {
        return totalOrdersCount;
    }

    public void setTotalOrdersCount(Integer totalOrdersCount) {
        this.totalOrdersCount = totalOrdersCount;
    }

    public Integer getTotalUnitsSold() {
        return totalUnitsSold;
    }

    public void setTotalUnitsSold(Integer totalUnitsSold) {
        this.totalUnitsSold = totalUnitsSold;
    }

    public Double getTotalRevenueGenerated() {
        return totalRevenueGenerated;
    }

    public void setTotalRevenueGenerated(Double totalRevenueGenerated) {
        this.totalRevenueGenerated = totalRevenueGenerated;
    }

    public Set<CategoryDTO> getCategories() {
        return categories;
    }

    public void setCategories(Set<CategoryDTO> categories) {
        this.categories = categories;
    }

    public Set<OrderSummaryAdminDTO> getOrdersSummary() {
        return ordersSummary;
    }

    public void setOrdersSummary(Set<OrderSummaryAdminDTO> ordersSummary) {
        this.ordersSummary = ordersSummary;
    }
}