package com.diniz.springbootstudy.controllers.exceptions;

import com.diniz.springbootstudy.services.exceptions.DatabaseException;
import com.diniz.springbootstudy.services.exceptions.ResourceNotFoundException;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.time.Instant;

/*
 * @ControllerAdvice:
 * Intercepts exceptions thrown across all Controllers in the application.
 * Acts as a global interceptor (AOP - Aspect Oriented Programming)
 * allowing centralized error handling in a single place, avoiding
 * redundant try-catch blocks in routes/controllers.
 */
@ControllerAdvice
public class ResourceExceptionHandler {

    // ========================================================================
    // EXCEPTION HANDLER METHOD: ResourceNotFoundException (HTTP 404)
    // ========================================================================
    @ExceptionHandler(ResourceNotFoundException.class)

    /*
     * StandardError defines the structure of the error response returned to the client.
     *
     * This class formats exceptions into a standardized JSON error response containing:
     * - timestamp: moment when the error occurred
     * - status: HTTP status code
     * - error: error description
     * - message: detailed exception message
     * - path: requested endpoint where the error happened
     *
     * ============================================================================
     * JSON ERROR RESPONSE EXAMPLE GENERATED BY StandardError
     * ============================================================================
     *
     * HTTP Status: 404 NOT FOUND
     *
     * Response Body:
     * {
     *   "timestamp": "2026-08-10T18:30:00Z",
     *   "status": 404,
     *   "error": "Resource not found",
     *   "message": "Resource not found. Id: 99",
     *   "path": "/users/99"
     * }
     * ============================================================================
     */
    /*
     * The name of this method: resourceNotFound
     *
     * This method is not called directly anywhere in the application code.
     * In pure Java, this could appear as unused code.
     * However, Spring automatically invokes this method at runtime through
     * the @ExceptionHandler annotation when a ResourceNotFoundException occurs.
     */
    public ResponseEntity<StandardError> resourceNotFound(
            // Arguments:
            // ResourceNotFoundException e → custom exception thrown by the service layer, containing the error details
            // HttpServletRequest request → represents the current HTTP request, providing information such as the request path
            ResourceNotFoundException e,
            HttpServletRequest request
    ) {
        String error = "Resource not found";
        HttpStatus status = HttpStatus.NOT_FOUND; // status 404

        /*
         * Creates an instance of StandardError to build the error response body.
         * It receives all required information about the exception and the HTTP request.
         */
        StandardError standard_err = new StandardError(
                Instant.now(),              // Current timestamp when the error occurred
                status.value(),             // HTTP status code value from the HttpStatus object
                error,                      // Generic error category/description
                e.getMessage(),             // Detailed message provided by the custom exception
                request.getRequestURI()     // URI path from the current HTTP request
        );

        return ResponseEntity.status(status).body(standard_err);
    }

    // ========================================================================
    // EXCEPTION HANDLER METHOD: DatabaseException (HTTP 400)
    // ========================================================================
    /*
     * Intercepts database integrity violation exceptions
     * (e.g., attempting to delete a user with associated orders / ConstraintViolationException).
     *
     * Mapped to HTTP 400 BAD REQUEST to indicate that the request could not
     * be processed due to business rule or database constraints.
     */
    @ExceptionHandler(DatabaseException.class)
    public ResponseEntity<StandardError> database(
            DatabaseException e,
            HttpServletRequest request
    ) {
        String error = "Database error";
        HttpStatus status = HttpStatus.BAD_REQUEST; // status 400

        StandardError standard_err = new StandardError(
                Instant.now(),
                status.value(),
                error,
                e.getMessage(),
                request.getRequestURI()
        );

        return ResponseEntity.status(status).body(standard_err);
    }

    // ========================================================================
    // EXCEPTION HANDLER METHOD: MethodArgumentNotValidException (HTTP 422)
    // ========================================================================
    /*
     * Intercepts DTO validation failures triggered by Bean Validation (@Valid, @NotNull, @Size, etc.).
     *
     * Returns HTTP 422 UNPROCESSABLE CONTENT along with the ValidationError subclass,
     * which extends StandardError and includes a detailed list containing the field name
     * and the specific error message for each invalid property.
     */
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ValidationError> validation(
            MethodArgumentNotValidException e,
            HttpServletRequest request
    ) {
        String error = "Validation exception";
        // UNPROCESSABLE_ENTITY deprecated -> use UNPROCESSABLE_CONTENT
        HttpStatus status = HttpStatus.UNPROCESSABLE_CONTENT; // status 422

        ValidationError err = new ValidationError(
                Instant.now(),
                status.value(),
                error,
                "Validation failed for one or more fields",
                request.getRequestURI()
        );

        /*
         * e.getBindingResult().getFieldErrors() retrieves all field validation errors.
         * The loop populates the ValidationError object by calling addError(field, defaultMessage)
         * to expose the exact error for each attribute in the JSON response.
         */
        for (FieldError f : e.getBindingResult().getFieldErrors()) {
            err.addError(f.getField(), f.getDefaultMessage());
        }

        return ResponseEntity.status(status).body(err);
    }
}