package com.diniz.springbootstudy.controllers.exceptions;

import com.diniz.springbootstudy.services.exceptions.DatabaseException;
import com.diniz.springbootstudy.services.exceptions.ResourceNotFoundException;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;

import java.time.Instant;

// WE USE THIS CLASS TO TREAT THE ERRORS MANUALLY
@ControllerAdvice // Intercepts exceptions thrown across the application
public class ResourceExceptionHandler {

    //1º -METHOD ->  resourceNotFound
    // Uses the ResourceNotFoundException class reference to identify which service-layer exceptions should be intercepted.
    // This custom exception extends RuntimeException and carries the error message that will be returned in the response.
    @ExceptionHandler(ResourceNotFoundException.class)

    /*
     * StandardError defines the structure of the error response returned to the client.
     *
     * This class formats exceptions into a standardized JSON error response containing:
     * - timestamp: moment when the error occurred
     * - status: HTTP status code
     * - error: error description
     * - message: detailed exception message
     * - path: requested endpoint where the error happened
     *
     * ============================================================================
     * JSON ERROR RESPONSE EXAMPLE GENERATED BY StandardError
     * ============================================================================
     *
     * HTTP Status: 404 NOT FOUND
     *
     * Response Body:
     * {
     *   "timestamp": "2026-08-10T18:30:00Z",
     *   "status": 404,
     *   "error": "Resource not found",
     *   "message": "Resource not found. Id: 99",
     *   "path": "/users/99"
     * }
     * ============================================================================
     */
    /*
     * The name of this method: resourceNotFound
     *
     * This method is not called directly anywhere in the application code.
     * In pure Java, this could appear as unused code.
     * However, Spring automatically invokes this method at runtime through
     * the @ExceptionHandler annotation when a ResourceNotFoundException occurs.
     */
    public ResponseEntity<StandardError> resourceNotFound(
            // Arguments:
            // ResourceNotFoundException e → custom exception thrown by the service layer, containing the error details
            // HttpServletRequest request → represents the current HTTP request, providing information such as the request path
            ResourceNotFoundException e,
            HttpServletRequest request
    ) {
        String error = "Resource not found";
        HttpStatus status = HttpStatus.NOT_FOUND; // status 404

        /*
         * Creates an instance of StandardError to build the error response body.
         * It receives all required information about the exception and the HTTP request.
         */
        StandardError err = new StandardError(
                // The StandardError constructor requires the following information

                Instant.now(),              // Current timestamp when the error occurred
                status.value(),             // HTTP status code value from the HttpStatus object
                error,                      // Error description defined in this handler
                e.getMessage(),             // Message from the custom ResourceNotFoundException
                request.getRequestURI()     // URI path from the current HTTP request
        );

        return ResponseEntity.status(status).body(err);
    }

    @ExceptionHandler(DatabaseException.class)
    public ResponseEntity<StandardError> database(DatabaseException e, HttpServletRequest request) {
        String error = "Database error";
        HttpStatus status = HttpStatus.BAD_REQUEST;

        StandardError err = new StandardError(
                Instant.now(),
                status.value(),
                error,
                e.getMessage(),
                request.getRequestURI()
        );

        return ResponseEntity.status(status).body(err);
    }

    // ========================================================================
    // EXCEPTION HANDLER METHOD: MethodArgumentNotValidException (HTTP 422)
    // ========================================================================
    // Captura as falhas das anotações do Bean Validation (@Valid) nos DTOs
    // e retorna a lista detalhada de campos inválidos no JSON.
    // ========================================================================
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ValidationError> validation(MethodArgumentNotValidException e, HttpServletRequest request) {
        String error = "Validation exception";
        HttpStatus status = HttpStatus.UNPROCESSABLE_ENTITY; // 422 UNPROCESSABLE ENTITY

        ValidationError err = new ValidationError(
                Instant.now(),
                status.value(),
                error,
                "Validation failed for one or more fields",
                request.getRequestURI()
        );

        // Mapeia cada erro de campo disparado pelo Spring para a lista do ValidationError
        for (FieldError f : e.getBindingResult().getFieldErrors()) {
            err.addError(f.getField(), f.getDefaultMessage());
        }

        return ResponseEntity.status(status).body(err);
    }
}