package com.diniz.springbootstudy.controllers.exceptions;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;

// ============================================================================
// STANDARD ERROR PAYLOAD LAYER
// ============================================================================
// Purpose:
// Structures and standardizes the JSON response body when an exception occurs in the API.
//
// Follows standard REST API error payload specifications:
// - timestamp: UTC Instant when the error occurred.
// - status: HTTP status code integer (e.g., 404, 400, 500).
// - error: Short description of the HTTP status phrase.
// - message: Detailed business or validation exception message.
// - path: URI endpoint path requested by the client.
// ============================================================================

/**
 * DTO representing the standardized JSON response body returned for API errors.
 */
public class StandardError implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    private Instant timestamp;
    private Integer status; // error code
    private String error; //the proper error
    private String message;  // the message of error
    private String path; // the path  http of error

    // Default Constructor (required for JSON serialization frameworks like Jackson)
    public StandardError() {
    }

    // Parameterized Constructor
    public StandardError(Instant timestamp, Integer status, String error, String message, String path) {
        this.timestamp = timestamp;
        this.status = status;
        this.error = error;
        this.message = message;
        this.path = path;
    }

    // ========================================================================
    // GETTERS AND SETTERS
    // ========================================================================

    public Instant getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
}

/*
 ============================================================================
 JSON ERROR RESPONSE EXAMPLE GENERATED BY STANDARD ERROR
 ============================================================================

 HTTP Status: 404 NOT FOUND
 Response Body (JSON):
 {
   "timestamp": "2026-08-10T18:30:00Z",
   "status": 404,
   "error": "Resource not found",
   "message": "Resource not found. Id: 99",
   "path": "/users/99"
 }
 ============================================================================
*/